# Data
train_data_dir: "data/train"
tomo_types:
  - "denoised"

# Patch Settings
patch_size: 128
num_classes: 7

# Training hyperparameters
learning_rate: 0.001
num_epochs: 2000
batch_size_train: 1
batch_size_valid: 2
num_workers: 1
patience: 100
load_from_checkpoint_dir: "checkpoint_pretraining"
checkpoint_dir_name: "checkpoint_finetune_denoised"

ids:
  - "TS_5_4"
  - "TS_6_4"
  - "TS_69_2"
  - "TS_6_6"
  - "TS_73_6"
  - "TS_86_3"
  - "TS_99_9"
