# Data
train_data_dir: "data/train"
tomo_types:
  - "denoised"
  - "ctfdeconvolved"
  - "isonetcorrected"

# Patch Settings
patch_size: 128
num_classes: 7

# Training hyperparameters
learning_rate: 0.001
num_epochs: 2000
batch_size_train: 1
batch_size_valid: 2
num_workers: 1
patience: 100
#load_from_checkpoint: "/home/clay/research/kaggle/czii-8th-solution/T_S___0-best-checkpoint-epoch=385-val_dice_mean=0.5779-val_loss=0.5731.ckpt"  # NOTE: add the checkpoint path here
load_from_checkpoint: "/home/clay/research/kaggle/kaggle_czii/data/deeper-2-model-weight/TS_0-best-checkpoint-epoch=259-val_dice_mean=0.5822-val_loss=0.5726.ckpt"
checkpoint_dir_name: "checkpoint_finetune_all"

ids:
  - "TS_5_4"
  - "TS_6_4"
  - "TS_69_2"
  - "TS_6_6"
  - "TS_73_6"
  - "TS_86_3"
  - "TS_99_9"
